force-app/main/default/objects/Mailchimp_Batch_Operation__c/Mailchimp_Batch_Operation__c.object-meta.xml
<CustomObject>
    <description>Tracks the status of a batch operation submitted to Mailchimp.</description>
    <label>Mailchimp Batch Operation</label>
    <nameField>
        <label>Mailchimp Batch Operation ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailchimp Batch Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;pending&quot;</defaultValue>
    <description>The status of the batch call.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>preprocessing</fullName>
            </value>
            <value>
                <fullName>started</fullName>
            </value>
            <value>
                <fullName>finalizing</fullName>
            </value>
            <value>
                <fullName>finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Submitted_At__c.field-meta.xml
<CustomField>
    <fullName>Submitted_At__c</fullName>
    <label>Submitted At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/MailchimpSyncStatus__c.object-meta.xml
<CustomObject>
    <description>Tracks the sync status for individual contacts.</description>
    <label>Mailchimp Sync Status</label>
    <nameField>
        <label>Mailchimp Sync Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailchimp Sync Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mailchimp Sync Statuses</relationshipLabel>
    <relationshipName>Mailchimp_Sync_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The contact&#39;s e-mail address, used internally by the sync process.</description>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/LastChanged__c.field-meta.xml
<CustomField>
    <fullName>LastChanged__c</fullName>
    <description>Date and time the list member corresponding to this contact was updated in Mailchimp.</description>
    <label>Last changed in Mailchimp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MailchimpJobsTest.cls
@isTest
private class MailchimpJobsTest {
    class MailchimpApiMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse resp = new HttpResponse();
            resp.setStatusCode(200);
            if (req.getEndpoint().startsWith('batches')) {
                resp.setBody('');
            }
            resp.setBody('{}');
            return resp;
        }
    }

    @isTest static void testMailchimpSyncJob() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();
        Integer nextYear = Date.today().year() + 1;
        String jobId = System.schedule(
            'MailchimpSyncJob',
            '0 0 0 26 11 ? ' + nextYear,
            new MailchimpSyncJob()
        );
        CronTrigger ct =
            [SELECT Id, CronExpression, TimesTriggered, NextFireTime
	         FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(nextYear + '-11-26 00:00:00',
            String.valueOf(ct.NextFireTime));
        Test.stopTest();
    }

    @isTest static void testPullInterestsJob() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();
        String jobId = System.enqueueJob(new MailchimpPullInterestsJob());
        Test.stopTest();

        AsyncApexJob jobInfo = [SELECT Status FROM AsyncApexJob WHERE Id = :jobId];
        System.assertEquals('Completed', jobInfo.Status);
    }

    @isTest static void testPullJob() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();
        MailchimpPullJob job = new MailchimpPullJob(200, 0);
        String jobId = System.enqueueJob(job);
        Test.stopTest();

        AsyncApexJob jobInfo = [SELECT Status FROM AsyncApexJob WHERE Id = :jobId];
        System.assertEquals('Completed', jobInfo.Status);
    }

    @isTest static void testPushJob() {
        Contact testContact = new Contact(
            FirstName='Joe',
            LastName='Schmoe',
            Email='joe.schmoe@example.com'
        );
        insert testContact;
        MailchimpSyncStatus__c testStatus = new MailchimpSyncStatus__c(
            Contact__c=testContact.Id,
            Email__c='joe.schmoe@example.com',
            LastChanged__c=Datetime.newInstanceGmt(2019, 9, 17, 10, 2, 55)
        );
        insert testStatus;

        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();
        Id jobId = Database.executeBatch(new MailchimpPushJob());
        Test.stopTest();

        AsyncApexJob jobInfo = [SELECT Status FROM AsyncApexJob WHERE Id = :jobId];
        System.assertEquals('Completed', jobInfo.Status);
    }

    @isTest static void testUpdateBatchesJob() {
        Mailchimp_Batch_Operation__c batch = new Mailchimp_Batch_Operation__c(
            Name='2av7lDQzO94',
            Status__c='pending',
            Submitted_At__c=Datetime.newInstance(2019, 11, 10, 9, 8, 7)
        );
        insert batch;

        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();
        MailchimpUpdateBatchesJob job = new MailchimpUpdateBatchesJob();
        String jobId = Database.executeBatch(job);
        Test.stopTest();

        AsyncApexJob jobInfo = [SELECT Status FROM AsyncApexJob WHERE Id = :jobId];
        System.assertEquals('Completed', jobInfo.Status);
    }
}