force-app/main/default/objects/Mailchimp_Batch_Operation__c/Mailchimp_Batch_Operation__c.object-meta.xml
<CustomObject>
    <description>Tracks the status of a batch operation submitted to Mailchimp.</description>
    <label>Mailchimp Batch Operation</label>
    <nameField>
        <label>Mailchimp Batch Operation ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailchimp Batch Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailchimp_Sync_Error__c/Mailchimp_Sync_Error__c.object-meta.xml
<CustomObject>
    <description>Represents an error that occurred during the Salesforce&lt;-&gt;Mailchimp sync process.</description>
    <label>Mailchimp Sync Error</label>
    <nameField>
        <displayFormat>E-{0000000}</displayFormat>
        <label>Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mailchimp Sync Errors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailchimp_Sync_Error__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If the error occurred on a specific contact, the contact on which it occurred</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mailchimp Sync Errors</relationshipLabel>
    <relationshipName>Mailchimp_Sync_Errors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Sync_Error__c/fields/Detail__c.field-meta.xml
<CustomField>
    <fullName>Detail__c</fullName>
    <description>A human-readable explanation specific to this occurrence of the problem.</description>
    <label>Detail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Sync_Error__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>What stage of the sync process the error occurred at</description>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0 - Fetch contacts from Mailchimp</fullName>
            </value>
            <value>
                <fullName>1 - Add/update contacts in Mailchimp</fullName>
            </value>
            <value>
                <fullName>2 - Add/update tags in Mailchimp</fullName>
            </value>
            <value>
                <fullName>3 - Mark Salesforce contacts as synced</fullName>
            </value>
            <value>
                <fullName>4 - Check Mailchimp batch job status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mailchimp_Sync_Error__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>A short summary of the problem type. It doesn&#39;t change based on the occurrence of the problem.</description>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MailchimpSyncController.cls
public with sharing class MailchimpSyncController {
    public String contactsNeedingSync { get; private set; }
    public String lastSyncCompletedAt { get; private set; }
    public String jobsInProgress { get; private set; }
    public List<Mailchimp_Sync_Error__c> recentSyncErrors { get; private set; }
    public List<Mailchimp_Batch_Operation__c> unfinishedBatchOperations { get; private set; }
    public List<AsyncApexJob> recentJobs { get; private set; }

    public void fetchData() {
        MailchimpSyncManager mailchimp = new MailchimpSyncManager();
        Integer contactsCount = mailchimp.contactsCount();
        this.contactsNeedingSync = contactsCount > 0 ?
                String.valueOf(contactsCount) :
                'No';
        Datetime lastSyncCompletedAt = mailchimp.lastSyncCompletedAt();
        this.lastSyncCompletedAt = lastSyncCompletedAt == null ?
            'No sync has been performed yet.' :
            'Last sync finished at ' + lastSyncCompletedAt.format() + '.';
        this.recentSyncErrors =
            [SELECT Id, Name, CreatedDate, Stage__c, Contact__c, Title__c, Detail__c
             FROM Mailchimp_Sync_Error__c
             ORDER BY CreatedDate DESC LIMIT 20];
        this.unfinishedBatchOperations = mailchimp.unfinishedBatches(20);
        this.recentJobs =
            [SELECT Id, ApexClass.Name, CreatedDate, Status, ExtendedStatus, NumberOfErrors
             FROM AsyncApexJob
             WHERE ApexClassID IN (
                SELECT Id FROM ApexClass WHERE Name IN ('MailchimpPullInterestsJob', 'MailchimpPullJob', 'MailchimpPushJob', 'MailchimpSyncJob')
             )
             ORDER BY CreatedDate DESC LIMIT 10];
        Integer jobsInProgress = mailchimp.inProgressJobsCount();
        this.jobsInProgress = jobsInProgress > 0 ?
            String.valueOf(jobsInProgress) :
            'No';
    }

    public PageReference updateContacts() {
        PageReference redirect = ApexPages.currentPage();
        redirect.setRedirect(true);

        System.enqueueJob(new MailchimpPullInterestsJob(new MailchimpPullJob(400, 0)));

        return redirect;
    }

    public PageReference syncAllContacts() {
        PageReference redirect = ApexPages.currentPage();
        redirect.setRedirect(true);

        System.enqueueJob(new MailchimpPullInterestsJob(new MailchimpPullJob(400, 0, false)));

        return redirect;
    }

    public PageReference updateBatches() {
        PageReference redirect = ApexPages.currentPage();
        redirect.setRedirect(true);

        MailchimpSyncManager mailchimp = new MailchimpSyncManager();
        mailchimp.updateBatches();

        return redirect;
    }
}