force-app/main/default/objects/Account/fields/CY_1_contribution_revenue__c.field-meta.xml
<CustomField>
    <fullName>CY_1_contribution_revenue__c</fullName>
    <formula>X2018_contribution_revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CY-1 contribution revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CY_2_contribution_revenue__c.field-meta.xml
<CustomField>
    <fullName>CY_2_contribution_revenue__c</fullName>
    <formula>X2017_contribution_revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CY-2 contribution revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CY_3_contribution_revenue__c.field-meta.xml
<CustomField>
    <fullName>CY_3_contribution_revenue__c</fullName>
    <formula>X2016_contribution_revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CY-3 contribution revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/CY_contribution_revenue__c.field-meta.xml
<CustomField>
    <fullName>CY_contribution_revenue__c</fullName>
    <formula>X2019_contribution_revenue__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CY contribution revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Membership_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Membership_Expiration_Date__c</fullName>
    <description>Calculated MinnPost membership expiration date, for use in automated renewal reminders.</description>
    <formula>IF(
  OR(
    SF_Record_Type__c=&quot;Organization&quot;,
    Lifetime_Donations_New__c &lt;= 0,
    OR(
      Lifetime_Donations_New__c &gt;= 10000,
      npo02__Best_Gift_Year_Total__c &gt;=5000,
      CY_contribution_revenue__c &gt;=1000, 
      CY_1_contribution_revenue__c &gt;=1000, 
      Membership_level_qualification_amount__c &gt;=1000
    ),
    Active_sustainer__c 
  ),
  NULL,
  IF(
    MONTH(npo02__LastCloseDate__c)=12,
    DATE(
      YEAR(npo02__LastCloseDate__c)+2,
      1,
      1
    ),    
    DATE(
      YEAR(npo02__LastCloseDate__c)+1,
      MONTH(npo02__LastCloseDate__c)+1,
      1
    )
  )
)</formula>
    <inlineHelpText>Calculated MinnPost membership expiration date, for use in automated renewal reminders.</inlineHelpText>
    <label>Membership Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Drupal_ID__c.field-meta.xml
<CustomField>
    <fullName>Drupal_ID__c</fullName>
    <label>Drupal ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Drupal_Username__c.field-meta.xml
<CustomField>
    <fullName>Drupal_Username__c</fullName>
    <description>Username from MinnPost.com Drupal system.</description>
    <inlineHelpText>Username from MinnPost.com Drupal system.</inlineHelpText>
    <label>Drupal Username</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailchimpEmailHash__c.field-meta.xml
<CustomField>
    <fullName>MailchimpEmailHash__c</fullName>
    <description>The MD5 hash of the lowercase version of the contact&#39;s e-mail address, used as an identifier by the Mailchimp API.</description>
    <externalId>true</externalId>
    <label>Mailchimp Email Hash</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/MailchimpMemberRating__c.field-meta.xml
<CustomField>
    <fullName>MailchimpMemberRating__c</fullName>
    <description>Member rating synced automatically from Mailchimp.</description>
    <label>Mailchimp Member Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/Mailchimp_Batch_Operation__c.object-meta.xml
<CustomObject>
    <description>Tracks the status of a batch operation submitted to Mailchimp.</description>
    <label>Mailchimp Batch Operation</label>
    <nameField>
        <label>Mailchimp Batch Operation ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailchimp Batch Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Completed_At__c.field-meta.xml
<CustomField>
    <fullName>Completed_At__c</fullName>
    <label>Completed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Errored_Operations__c.field-meta.xml
<CustomField>
    <fullName>Errored_Operations__c</fullName>
    <label>Errored Operations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Finished_Operations__c.field-meta.xml
<CustomField>
    <fullName>Finished_Operations__c</fullName>
    <label>Finished Operations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Response_Body_URL__c.field-meta.xml
<CustomField>
    <fullName>Response_Body_URL__c</fullName>
    <description>The URL of the gzipped archive of the results of all the operations. Only available for 10 minutes after the batch completes.</description>
    <label>Response Body URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;pending&quot;</defaultValue>
    <description>The status of the batch call.</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>preprocessing</fullName>
            </value>
            <value>
                <fullName>started</fullName>
            </value>
            <value>
                <fullName>finalizing</fullName>
            </value>
            <value>
                <fullName>finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Submitted_At__c.field-meta.xml
<CustomField>
    <fullName>Submitted_At__c</fullName>
    <label>Submitted At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Mailchimp_Batch_Operation__c/fields/Total_Operations__c.field-meta.xml
<CustomField>
    <fullName>Total_Operations__c</fullName>
    <label>Total Operations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/MailchimpFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>Mailchimp Field Mapping</label>
    <pluralLabel>Mailchimp Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>push</fullName>
                <default>true</default>
                <label>Salesforce → Mailchimp</label>
            </value>
            <value>
                <fullName>pull</fullName>
                <label>Mailchimp → Salesforce</label>
            </value>
            <value>
                <fullName>sync</fullName>
                <label>Use for sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Mailchimp_Member_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Mailchimp_Member_Attribute__c</fullName>
    <label>Mailchimp Member Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email_address</fullName>
                <default>true</default>
                <label>email_address</label>
            </value>
            <value>
                <fullName>email_client</fullName>
            </value>
            <value>
                <fullName>email_type</fullName>
            </value>
            <value>
                <fullName>ip_opt</fullName>
            </value>
            <value>
                <fullName>ip_signup</fullName>
            </value>
            <value>
                <fullName>language</fullName>
            </value>
            <value>
                <fullName>member_rating</fullName>
            </value>
            <value>
                <fullName>source</fullName>
            </value>
            <value>
                <fullName>status</fullName>
            </value>
            <value>
                <fullName>tags_count</fullName>
            </value>
            <value>
                <fullName>timestamp_opt</fullName>
            </value>
            <value>
                <fullName>timestamp_signup</fullName>
            </value>
            <value>
                <fullName>vip</fullName>
            </value>
            <value>
                <fullName>id</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Mailchimp_Merge_Field_Tag__c.field-meta.xml
<CustomField>
    <fullName>Mailchimp_Merge_Field_Tag__c</fullName>
    <description>The *|MERGE|* tag to use to map this field in Mailchimp (e.g. FNAME, LNAME)</description>
    <inlineHelpText>The *|MERGE|* tag to use to map this field in Mailchimp (e.g. FNAME, LNAME)</inlineHelpText>
    <label>Mailchimp *|MERGE|* Field Tag</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Push_To_Mailchimp_As__c.field-meta.xml
<CustomField>
    <fullName>Push_To_Mailchimp_As__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Push To Mailchimp As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*|MERGE|* Field</fullName>
            </value>
            <value>
                <fullName>Tag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Salesforce_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object_API_Name__c</fullName>
    <defaultValue>&quot;Contact&quot;</defaultValue>
    <description>The API name of the standard or custom object to map this field onto.</description>
    <inlineHelpText>The API name of the standard or custom object to map this field onto.</inlineHelpText>
    <label>Salesforce Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpSettings__c/MailchimpSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Mailchimp Settings</label>
</CustomObject>

force-app/main/default/objects/MailchimpSettings__c/fields/AudienceID__c.field-meta.xml
<CustomField>
    <fullName>AudienceID__c</fullName>
    <description>Mailchimp Audience ID</description>
    <externalId>true</externalId>
    <label>Audience ID</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/MailchimpSyncStatus__c.object-meta.xml
<CustomObject>
    <description>Tracks the sync status for individual contacts.</description>
    <label>Mailchimp Sync Status</label>
    <nameField>
        <label>Mailchimp Sync Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mailchimp Sync Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/BatchID__c.field-meta.xml
<CustomField>
    <fullName>BatchID__c</fullName>
    <description>The ID of a pending Mailchimp batch operation that affects this contact.</description>
    <externalId>true</externalId>
    <label>Mailchimp Batch Operation</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mailchimp Sync Statuses</relationshipLabel>
    <relationshipName>Mailchimp_Sync_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>The contact&#39;s e-mail address, used internally by the sync process.</description>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/LastChanged__c.field-meta.xml
<CustomField>
    <fullName>LastChanged__c</fullName>
    <description>Date and time the list member corresponding to this contact was updated in Mailchimp.</description>
    <label>Last changed in Mailchimp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/MailchimpSyncStatus__c/fields/LastPushed__c.field-meta.xml
<CustomField>
    <fullName>LastPushed__c</fullName>
    <description>Date/time this contact was last pushed to Mailchimp.</description>
    <label>Last pushed to Mailchimp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MailchimpSyncManagerTest.cls
@isTest
private class MailchimpSyncManagerTest {
    class MailchimpApiMock implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse resp = new HttpResponse();
            resp.setStatusCode(200);
            resp.setHeader('Content-Type', 'application/json');

            String endpoint = req.getEndpoint().substringAfter('/');
            System.debug(req.getMethod() + ' ' + endpoint);
            if (req.getMethod() == 'POST' && endpoint == 'batches') {
                resp.setBody('{"id":"rA45kKQWre","status":"pending","total_operations":1,"submitted_at":"2019-09-17T10:55:09Z"}');
            }
            else if (endpoint.startsWith('batches')) {
                resp.setBody('{"id":"rA45kKQWre","status":"finished","total_operations":1,"finished_operations":1,"errored_operations":0,"submitted_at":"2019-09-17T10:55:09Z","completed_at":"2019-09-19T10:56:10Z"}');
            }
            else if (req.getMethod() == 'GET' && endpoint.startsWith('lists/3528e74526/members')) {
                MailchimpAPI.Subscriber sub = new MailchimpAPI.Subscriber();
                sub.id = '7ec16a886e5baa2052c20bb16464a45b';
                sub.email_address = 'helen1604@example.com';
                sub.status = 'subscribed';
                sub.member_rating = 3;
                sub.last_changed = Datetime.newInstanceGmt(2019, 9, 17, 10, 55, 9);
                sub.merge_fields = new Map<String, String>{};
                sub.interests = new Map<String, Boolean>{};
                MailchimpSyncManager.MembersResponse mr =
                    new MailchimpSyncManager.MembersResponse();
                mr.members = new List<MailchimpAPI.Subscriber>{ sub };
                mr.total_items = 1;
                resp.setBody(JSON.serialize(mr));
            }
            else {
                resp.setBody('{}');
            }

            return resp;
        }
    }

    @TestSetup
    static void setup() {
        MailchimpSettings__c settings = MailchimpSettings__c.getOrgDefaults();
        settings.AudienceID__c = '3528e74526';
        upsert settings;

        Mailchimp_Batch_Operation__c batch = new Mailchimp_Batch_Operation__c(
            Name='rA45kKQWre',
            Status__c='pending',
            Submitted_At__c=Datetime.newInstanceGmt(2019, 9, 11, 10, 10, 50)
        );
        insert batch;
        Mailchimp_Batch_Operation__c finishedBatch = new Mailchimp_Batch_Operation__c(
            Name='MfpxUuhLKC',
            Status__c='finished',
            Submitted_At__c=Datetime.newInstanceGmt(2019, 9, 10, 9, 9, 50),
            Completed_At__c=Datetime.newInstanceGmt(2019, 9, 10, 9, 10, 50),
            Total_Operations__c=1,
            Errored_Operations__c=0,
            Finished_Operations__c=1,
            Response_Body_URL__c='https://s3.amazonaws.com/example/batch.tgz'
        );
        insert finishedBatch;

        Contact[] testContacts = new List<Contact>{
            new Contact(
                FirstName='Joe',
                LastName='Schmoe',
                Email='joe.schmoe@example.com'
            ),
            new Contact(
                FirstName='Julie',
                LastName='Schmoo',
                Email='jschmoo@example.com'
            ),
            new Contact(
                FirstName='Abdi',
                LastName='Mohammed',
                Email='mohabdi@example.com'
            ),
            new Contact(
                FirstName='Helen',
                LastName='Troius',
                Email='helen1604@example.com'
            ),
            new Contact(
                FirstName='Fujiwara',
                LastName='Morimoto',
                Email='mfuji@example.co.jp'
            )
        };
        Database.SaveResult[] results = Database.insert(testContacts);

        MailchimpSyncStatus__c[] testStatuses = new List<MailchimpSyncStatus__c>{
            // Pulled but never pushed back
            new MailchimpSyncStatus__c(
                Email__c='joe.schmoe@example.com',
                LastChanged__c=Datetime.newInstanceGmt(2019, 9, 17, 10, 2, 55)
            ),

            // jschmoo@example.com - Not in Mailchimp, should not be pushed
            null,

            // Already pushed, should not be pushed again
            new MailchimpSyncStatus__c(
                Email__c='mohabdi@example.com',
                LastChanged__c=Datetime.newInstanceGmt(2019, 9, 10, 9, 9, 9),
                // This will be (very slightly) greater than the contact's
                // LastModifiedDate
                LastPushed__c=Datetime.now()
            ),

            // Pulled but not pushed back yet
            new MailchimpSyncStatus__c(
                Email__c='helen1604@example.com',
                LastChanged__c=Datetime.newInstanceGmt(2019, 9, 12, 5, 5, 5),
                // A day ago is less than the contact's LastModifiedDate
                LastPushed__c=(Datetime.now() - 1)
            ),

            // Synced but tag operation still in progress, should show up in count
            new MailchimpSyncStatus__c(
                Email__c='mfuji@example.co.jp',
                BatchID__c='psBNCYMK33',
                LastChanged__c=Datetime.newInstanceGmt(2019, 9, 10, 9, 9, 9),
                // This will be (very slightly) greater than the contact's
                // LastModifiedDate
                LastPushed__c=Datetime.now()
            )
        };

        MailchimpSyncStatus__c[] statusesToInsert = new List<MailchimpSyncStatus__c>();
        for (Integer i = 0; i < results.size(); ++i) {
            MailchimpSyncStatus__c status = testStatuses[i];
            if (status == null) continue;

            status.Contact__c = results[i].getId();
            statusesToInsert.add(status);
        }
        insert statusesToInsert;
        for (Contact c : testContacts) {
            c.recalculateFormulas();
        }
    }

    static MailchimpSyncManager subject() {
        MailchimpFieldMapping__mdt[] fieldMappings = new List<MailchimpFieldMapping__mdt>{
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Id',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Id',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='SF_CONTACT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Email',
                Direction__c='sync',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Email',
                Mailchimp_Member_Attribute__c='email_address'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.FirstName',
                Direction__c='sync',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='FirstName',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='FNAME'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.LastName',
                Direction__c='sync',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='LastName',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='LNAME'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Drupal_ID',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Drupal_ID__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CMS_UID'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Drupal_Username',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Drupal_Username__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CMS_USER'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.MailchimpEmailHash',
                Direction__c='sync',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='MailchimpEmailHash__c',
                Mailchimp_Member_Attribute__c='id'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.MailchimpMemberRating',
                Direction__c='pull',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='MailchimpMemberRating__c',
                Mailchimp_Member_Attribute__c='member_rating'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.CY_contribution_revenue',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='CY_contribution_revenue__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CY_CONTRIB'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.CY_1_contribution_revenue',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='CY_1_contribution_revenue__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CY_1_CONT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.CY_2_contribution_revenue',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='CY_2_contribution_revenue__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CY_2_CONT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.CY_3_contribution_revenue',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='CY_3_contribution_revenue__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='CY_3_CONT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Id',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Id',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='SF_ACCOUNT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Membership_Expiration_Date',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Membership_Expiration_Date__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='MEMBER_EXP'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Membership_Level',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Membership_Level__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='MEMBER_LEV'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Membership_Level_Number',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Membership_Level_Number__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='MEMLEV_NUM'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Membership_level_qualification_a',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Membership_level_qualification_amount__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='MEMLEV_AMT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.Recurring_donations_Annualized_v',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='Recurring_donations_Annualized_value_new__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='RECURR_AMT'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Account.SF_Record_Type',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Account',
                Salesforce_Field_API_Name__c='SF_Record_Type__c',
                Push_To_Mailchimp_As__c='*|MERGE|* Field',
                Mailchimp_Merge_Field_Tag__c='SFACCTTYPE'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Active_sustainer_account',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Active_sustainer_account__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='Active sustainer'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.MinnPost_com_user_account',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='MinnPost_com_user_account__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='CMS user'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Current_member',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Current_member__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='Current member'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Lapsed_member',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Lapsed_member__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='Lapsed member'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Never_member',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Never_member__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='Never member'
            ),
            new MailchimpFieldMapping__mdt(
                MasterLabel='Contact.Is_partner_offer_eligible',
                Direction__c='push',
                Salesforce_Object_API_Name__c='Contact',
                Salesforce_Field_API_Name__c='Is_partner_offer_eligible__c',
                Push_To_Mailchimp_As__c='Tag',
                Mailchimp_Merge_Field_Tag__c='Partner offer eligible'
            )
        };

        return new MailchimpSyncManager(fieldMappings);
    }

    @isTest static void testContactsToSync() {
        Test.startTest();

        Contact[] contacts = subject().contactsToSync(200);
        System.debug(contacts);
        System.assertEquals(2, contacts.size());
        System.assertEquals('Helen', contacts[0].FirstName);
        System.assertEquals('Troius', contacts[0].LastName);
        System.assertEquals(
            'Household Account',
            contacts[0].Account.SF_Record_Type__c
        );
        System.assertEquals('Joe', contacts[1].FirstName);
        System.assertEquals('Schmoe', contacts[1].LastName);
        System.assertEquals(
            'Household Account',
            contacts[1].Account.SF_Record_Type__c
        );

        Test.stopTest();
    }

    @isTest static void testContactsCount() {
        Test.startTest();

        Integer count = subject().contactsCount();
        System.assertEquals(3, count);

        Test.stopTest();
    }

    @isTest static void testUnfinishedBatches() {
        Test.startTest();

        Mailchimp_Batch_Operation__c[] batches = subject().unfinishedBatches();
        System.assertEquals(1, batches.size());
        System.assertEquals('rA45kKQWre', batches[0].Name);

        Test.stopTest();
    }

    @isTest static void testLastSyncCompletedAt() {
        Test.startTest();

        Long delta = Datetime.now().getTime() -
            subject().lastSyncCompletedAt().getTime();
        System.debug('testLastSyncCompletedAt: delta = ' + delta);
        System.assert(
            delta < 30000 // 30s
        );

        Test.stopTest();
    }

    @isTest static void testUpdateBatches() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();

        subject().updateBatches();
        Mailchimp_Batch_Operation__c batch =
            [SELECT Name, Status__c, Completed_At__c, Total_Operations__c
             FROM Mailchimp_Batch_Operation__c
             WHERE Name = 'rA45kKQWre' LIMIT 1];
        System.assertEquals('finished', batch.Status__c);
        System.assertEquals(
            Datetime.newInstanceGmt(2019, 9, 19, 10, 56, 10),
            batch.Completed_At__c
        );
    }

    @isTest static void testPullAll() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();

        MailchimpSyncManager.PullResult result = subject().pullAll(1000, 0, false);
        System.assertEquals(MailchimpSyncManager.PullResult.DONE, result);

        Test.stopTest();
    }

    @isTest static void testPullAllSinceLastSync() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();

        MailchimpSyncManager.PullResult result = subject().pullAll(1000, 0);
        System.assertEquals(MailchimpSyncManager.PullResult.DONE, result);

        Test.stopTest();
    }

    @isTest static void testPushAll() {
        Test.setMock(HttpCalloutMock.class, new MailchimpApiMock());
        Test.startTest();

        MailchimpSyncManager mailchimp = subject();
        Contact[] contacts = mailchimp.contactsToSync(null);
        MailchimpSyncManager.Result result = mailchimp.pushAll(contacts);
        System.assert(!result.isError());
        System.assert(result.contactErrors.isEmpty());

        Test.stopTest();
    }
}