force-app/main/default/objects/MailchimpFieldMapping__mdt/MailchimpFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>Mailchimp Field Mapping</label>
    <pluralLabel>Mailchimp Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Default_Value__c.field-meta.xml
<CustomField>
    <fullName>Default_Value__c</fullName>
    <description>For &quot;Use for sync&quot; fields, the default value to be assigned when creating new records.</description>
    <inlineHelpText>For &quot;Use for sync&quot; fields, the default value to be assigned when creating new records.</inlineHelpText>
    <label>Default Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>push</fullName>
                <default>true</default>
                <label>Salesforce → Mailchimp</label>
            </value>
            <value>
                <fullName>pull</fullName>
                <label>Mailchimp → Salesforce</label>
            </value>
            <value>
                <fullName>sync</fullName>
                <label>Use for sync</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Mailchimp_Member_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Mailchimp_Member_Attribute__c</fullName>
    <label>Mailchimp Member Attribute</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>email_address</fullName>
                <default>true</default>
                <label>email_address</label>
            </value>
            <value>
                <fullName>email_client</fullName>
            </value>
            <value>
                <fullName>email_type</fullName>
            </value>
            <value>
                <fullName>ip_opt</fullName>
            </value>
            <value>
                <fullName>ip_signup</fullName>
            </value>
            <value>
                <fullName>language</fullName>
            </value>
            <value>
                <fullName>member_rating</fullName>
            </value>
            <value>
                <fullName>source</fullName>
            </value>
            <value>
                <fullName>status</fullName>
            </value>
            <value>
                <fullName>tags_count</fullName>
            </value>
            <value>
                <fullName>timestamp_opt</fullName>
            </value>
            <value>
                <fullName>timestamp_signup</fullName>
            </value>
            <value>
                <fullName>vip</fullName>
            </value>
            <value>
                <fullName>id</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Mailchimp_Merge_Field_Tag__c.field-meta.xml
<CustomField>
    <fullName>Mailchimp_Merge_Field_Tag__c</fullName>
    <description>The *|MERGE|* tag to use to map this field in Mailchimp (e.g. FNAME, LNAME)</description>
    <inlineHelpText>The *|MERGE|* tag to use to map this field in Mailchimp (e.g. FNAME, LNAME)</inlineHelpText>
    <label>Mailchimp *|MERGE|* Field Tag</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Push_To_Mailchimp_As__c.field-meta.xml
<CustomField>
    <fullName>Push_To_Mailchimp_As__c</fullName>
    <defaultValue>&quot;&quot;</defaultValue>
    <label>Push To Mailchimp As</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>*|MERGE|* Field</fullName>
            </value>
            <value>
                <fullName>Tag</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Salesforce_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Field_API_Name__c</fullName>
    <label>Salesforce Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MailchimpFieldMapping__mdt/fields/Salesforce_Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Object_API_Name__c</fullName>
    <defaultValue>&quot;Contact&quot;</defaultValue>
    <description>The API name of the standard or custom object to map this field onto.</description>
    <inlineHelpText>The API name of the standard or custom object to map this field onto.</inlineHelpText>
    <label>Salesforce Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MailchimpFieldMappingsController.cls
public with sharing class MailchimpFieldMappingsController {
    public MailchimpFieldMapping__mdt[] fieldMappings {
        get {
            if (fieldMappings == null) {
                fieldMappings =
                    [SELECT Direction__c,
                            Salesforce_Object_API_Name__c,
                            Salesforce_Field_API_Name__c,
                            Push_To_Mailchimp_As__c,
                            Mailchimp_Merge_Field_Tag__c,
                            Mailchimp_Member_Attribute__c,
                            Default_Value__c
                     FROM MailchimpFieldMapping__mdt
                     ORDER BY Direction__c ASC,
                              Push_To_Mailchimp_As__c ASC,
                              Salesforce_Object_API_Name__c ASC,
                              Salesforce_Field_API_Name__c ASC];
            }
            return fieldMappings;
        }
        set;
    }

    public PageReference save() {
        return ApexPages.currentPage();
    }
}